In [6]:
#loading the csv file 
import os
print("wir sind:",os.getcwd())
os.chdir("C:/Users/Robert Glantz/feb26_bds_int_supply_chain/project_supply_chain/")
import pandas as pd
pd.set_option('display.max_columns', None)
df=pd.read_csv("src/data/clean/reviews_processed.csv",sep=",")

wir sind: C:\Users\Robert Glantz\feb26_bds_int_supply_chain\project_supply_chain\src\data\clean

In [7]:
from langdetect import detect, DetectorFactory
DetectorFactory.seed = 0  # für reproduzierbare Ergebnisse

def detect_lang(text):
    try:
        return detect(text)
    except:
        return "unknown"

#df["language"] = df["review_text"].astype(str).apply(detect_lang)
df["language"] = [detect_lang(t) for t in df["review_text"].astype(str)]
print(df["language"].value_counts())

df_not_en=df[df["language"]!="en"]
df_en=df[df["language"]=="en"]

language
en         11474
de           315
da           252
fr           224
ca           124
af           114
it            99
pt            89
no            73
nl            49
es            35
id            29
et            22
ro            19
hr            18
sv            16
so            16
sl            14
cy            12
tl            11
sk             6
sq             5
hu             4
pl             3
unknown        2
sw             2
cs             2
ru             2
uk             2
vi             2
lv             2
Name: count, dtype: int64

In [10]:
df_not_en.head(100)

,rating,review_text,date,location,supplier_response,verified,company,domain,review_text_clean,review_length,has_response,language
0,5.0,Alles top. Wenn man sich einmal registriert ha...,2025-08-29 20:26:37+00:00,NaN,NaN,0,thg-experten,de,top registriert läuft einreichung auszahlung j...,34,1,de
14,5.0,Alles top. Wenn man sich einmal registriert ha...,2025-08-29 20:26:37+00:00,DE,NaN,0,thg-experten,de,top registriert läuft einreichung auszahlung j...,90,1,de
126,5.0,Solide und diskrete Durchsetzung meiner Möglic...,2023-10-20 17:14:22+00:00,DE,NaN,0,thg-experten,de,solide diskrete durchsetzung möglichkeiten eig...,23,1,de
141,5.0,"Webseite übersichtlich und verständlich, zügig...",2023-10-12 13:16:48+00:00,DE,NaN,0,thg-experten,de,webseite übersichtlich verständlich zügige bea...,28,1,de
146,5.0,"Super price, fast delivery",2025-02-27 09:09:21+00:00,NaN,NaN,1,motorradreifendirekt,de,super price fast delivery,4,1,it
...,...,...,...,...,...,...,...,...,...,...,...,...
1241,5.0,"Rapide , simple et efficace",2021-11-01 11:16:27+00:00,FR,NaN,0,123pneus,fr,rapide simple et efficace,5,1,fr
1244,5.0,"Efficacité, respect de l'engagement. Ok",2021-07-04 09:42:10+00:00,FR,NaN,0,123pneus,fr,efficacité respect de l engagement ok,5,1,fr
1245,5.0,Top seller I’m a client since a very long time...,2021-04-26 08:08:10+00:00,FR,NaN,0,123pneus,fr,top seller client since long time never bad su...,50,1,fr
1246,5.0,"Excellent site, rapide et efficace",2021-04-26 07:41:05+00:00,FR,NaN,0,123pneus,fr,excellent site rapide et efficace,5,1,fr
1247,4.0,Rapide. Efficacité. Satisfaction,2020-12-04 06:39:41+00:00,FR,NaN,0,123pneus,fr,rapide efficacité satisfaction,3,1,fr

In [11]:
df_en.head(100)

,rating,review_text,date,location,supplier_response,verified,company,domain,review_text_clean,review_length,has_response,language
1,5.0,Thg- Experten made a great Job. However the po...,2024-06-27 20:24:20+00:00,NaN,NaN,0,thg-experten,de,thg experten made great job however politician...,36,1,en
2,4.0,Thg did what they promised to do and paid out ...,2025-10-26 16:31:30+00:00,NaN,NaN,0,thg-experten,de,thg promised paid expected thg bonus star trie...,32,1,en
3,4.0,Process to place the order was very easy. Info...,2024-04-29 15:50:33+00:00,NaN,NaN,0,thg-experten,de,process place order easy information period pr...,37,1,en
4,5.0,"All well done, efficient, fast and transparent...",2026-03-07 16:49:20+00:00,DE,NaN,0,thg-experten,de,well done efficient fast transparent process,8,1,en
5,5.0,"Everything is ok, good price",2026-01-07 19:05:38+00:00,DE,NaN,0,thg-experten,de,everything ok good price,5,1,en
...,...,...,...,...,...,...,...,...,...,...,...,...
97,5.0,"Not complicated, it was amazing to receive fin...",2024-03-03 13:56:37+00:00,DE,NaN,0,thg-experten,de,complicated amazing receive financial support ...,26,1,en
98,4.0,"After a long time, I received the THG bonus",2024-02-22 20:11:29+00:00,DE,NaN,0,thg-experten,de,long time received thg bonus,9,1,en
99,5.0,Simply and easily upload the data and then jus...,2024-02-22 11:01:05+00:00,DE,NaN,0,thg-experten,de,simply easily upload data wait everything done...,31,1,en
100,5.0,"Everything went well, transparently with regul...",2024-02-22 10:19:28+00:00,DE,NaN,0,thg-experten,de,everything went well transparently regular sta...,33,1,en
101,1.0,THG Expert advertises that it's pay-out is abo...,2024-02-16 09:23:12+00:00,DE,Wir schätzen Ihr Feedback und nehmen Ihre Anli...,1,thg-experten,de,thg expert advertises pay average definitely c...,35,1,en

In [23]:
df_not_en=df_not_en.reset_index(drop=True)
print(df_not_en["review_length"].sort_values(ascending=False).mean())

8.060140754958413

In [ ]:
from deep_translator import GoogleTranslator

translator = GoogleTranslator(source='auto', target='en')

df_not_en["review_text_en"] = df_not_en["review_text"].apply(lambda x: translator.translate(x) if pd.notna(x) else x)

In [ ]:
df_en["review_text_en"]=df_en["review_text"]
df_final=pd.concat([df_en,df_not_en])